FileName <- "/Users/nischaynidhi/Desktop/coursera/household_power_consumption.txt"
data_access <- read.table(FileName, header=TRUE, sep=";", stringsAsFactors=FALSE, dec=".")
subData <- data_access[data_access$Date %in% c("1/2/2007","2/2/2007") ,]
DateTime <- strptime(paste(subData$Date, subData$Time, sep=" "), "%d/%m/%Y %H:%M:%S") 
globalActivePower <- as.numeric(subData$Global_active_power)
globalReactivePower <- as.numeric(subData$Global_reactive_power)
Voltage <- as.numeric(subData$Voltage)
SubMetering1 <- as.numeric(subData$Sub_metering_1)
SubMetering2 <- as.numeric(subData$Sub_metering_2)
SubMetering3 <- as.numeric(subData$Sub_metering_3)
png("plot4.png", width=480, height=480)
par(mfrow = c(2, 2)) 
plot(DateTime, globalActivePower, type="l", xlab="", ylab="Global Active Power", cex=0.2)
plot(DateTime, Voltage, type="l", xlab="datetime", ylab="Voltage")
plot(DateTime, SubMetering1, type="l", ylab="Energy sub metering", xlab="")
lines(DateTime, SubMetering2, type="l", col="red")
lines(DateTime, SubMetering3, type="l", col="blue")
legend("topright", c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), lty=, lwd=2.5, col=c("black", "red", "blue"), bty="o")
plot(DateTime, globalReactivePower, type="l", xlab="datetime", ylab="Global_reactive_power")
dev.off()
